"""Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with **1** and **2**, the first terms will be: **1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...*** By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def even_fibonacci_numbers(max: int) -> int:
    """Find the sum of all even Fibonacci numbers below 4,000,000"""

    total = 2
    fn1 = 1
    fn2 = 2

    while True:
        fn = fn1 + fn2
        fn1 = fn2
        fn2 = fn
        if fn > max:
            break
        if fn % 2 == 0:
            total += fn
    print("total:", total)
    return total


if __name__ == "__main__":
    even_fibonacci_numbers(4000000)
